package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.12 12:25:29 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AllergeenitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa29 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa29() throws SailoException {    // Allergeenit: 29
    Allergeenit allergeenit = new Allergeenit(); 
    Allergeeni a1 = new Allergeeni(); 
    Allergeeni a2 = new Allergeeni(); 
    Allergeeni a3 = new Allergeeni(); 
    allergeenit.lisaa(a1); assertEquals("From: Allergeenit line: 38", 1, allergeenit.haeLkm()); 
    allergeenit.lisaa(a2); assertEquals("From: Allergeenit line: 39", 2, allergeenit.haeLkm()); 
    allergeenit.lisaa(a3); assertEquals("From: Allergeenit line: 40", 3, allergeenit.haeLkm()); 
    assertEquals("From: Allergeenit line: 42", a1, allergeenit.anna(0)); 
    assertEquals("From: Allergeenit line: 43", a2, allergeenit.anna(1)); 
    assertEquals("From: Allergeenit line: 44", a3, allergeenit.anna(2)); 
    try {
    allergeenit.anna(3); 
    fail("Allergeenit: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a1); 
    try {
    allergeenit.lisaa(a1); 
    fail("Allergeenit: 59 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHaeAllergeeniIdlla134 
   * @throws SailoException when error
   */
  @Test
  public void testHaeAllergeeniIdlla134() throws SailoException {    // Allergeenit: 134
    Allergeenit allergeenit = new Allergeenit(); 
    Allergeeni a1 = new Allergeeni(); 
    Allergeeni a2 = new Allergeeni(); 
    Allergeeni a3 = new Allergeeni(); 
    a1.rekisteroi(); assertEquals("From: Allergeenit line: 143", 1, a1.haeId()); 
    a2.rekisteroi(); assertEquals("From: Allergeenit line: 144", 2, a2.haeId()); 
    a3.rekisteroi(); assertEquals("From: Allergeenit line: 145", 3, a3.haeId()); 
    allergeenit.lisaa(a1); 
    allergeenit.lisaa(a2); 
    allergeenit.lisaa(a3); 
    assertEquals("From: Allergeenit line: 151", a1, allergeenit.haeAllergeeniIdlla(1)); 
    assertEquals("From: Allergeenit line: 152", a2, allergeenit.haeAllergeeniIdlla(2)); 
    assertEquals("From: Allergeenit line: 153", a3, allergeenit.haeAllergeeniIdlla(3)); 
    try {
    allergeenit.haeAllergeeniIdlla(4); 
    fail("Allergeenit: 154 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}