package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.03 11:00:33 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AllergeeniTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi43 */
  @Test
  public void testRekisteroi43() {    // Allergeeni: 43
    Allergeeni a1 = new Allergeeni(); 
    a1.rekisteroi(); assertEquals("From: Allergeeni line: 45", 1, a1.haeId()); 
    Allergeeni a2 = new Allergeeni(); 
    a2.rekisteroi(); assertEquals("From: Allergeeni line: 48", 2, a2.haeId()); 
    Allergeeni a3 = new Allergeeni(); 
    a3.rekisteroi(); assertEquals("From: Allergeeni line: 51", 3, a3.haeId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse133 */
  @Test
  public void testParse133() {    // Allergeeni: 133
    Allergeeni allergeeni = new Allergeeni(); 
    allergeeni.parse( "1|Gluteeni" ); 
    assertEquals("From: Allergeeni line: 136", 1, allergeeni.haeId()); 
    assertEquals("From: Allergeeni line: 137", true, allergeeni.toString().startsWith( "1|Gluteeni" )); 
    allergeeni.rekisteroi(); 
    int n = allergeeni.haeId(); 
    allergeeni.parse( "" + ( n + 20 )); 
    allergeeni.rekisteroi(); 
    assertEquals("From: Allergeeni line: 143", n + 20 + 1, allergeeni.haeId()); 
  } // Generated by ComTest END
}