package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.08 12:36:01 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AllergeeniTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi31 */
  @Test
  public void testRekisteroi31() {    // Allergeeni: 31
    Allergeeni a1 = new Allergeeni(); 
    a1.rekisteroi(); assertEquals("From: Allergeeni line: 33", 1, a1.haeId()); 
    Allergeeni a2 = new Allergeeni(); 
    a2.rekisteroi(); assertEquals("From: Allergeeni line: 36", 2, a2.haeId()); 
    Allergeeni a3 = new Allergeeni(); 
    a3.rekisteroi(); assertEquals("From: Allergeeni line: 39", 3, a3.haeId()); 
  } // Generated by ComTest END
}