package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.02.26 14:57:11 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RavintolatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa28 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa28() throws SailoException {    // Ravintolat: 28
    Ravintolat ravintolat = new Ravintolat(); 
    Ravintola r = new Ravintola(); 
    Ravintola r2 = new Ravintola(); 
    assertEquals("From: Ravintolat line: 34", 0, ravintolat.getLkm()); 
    ravintolat.lisaa(r); assertEquals("From: Ravintolat line: 36", 1, ravintolat.getLkm()); 
    ravintolat.lisaa(r2); assertEquals("From: Ravintolat line: 37", 2, ravintolat.getLkm()); 
    ravintolat.lisaa(r); assertEquals("From: Ravintolat line: 38", 3, ravintolat.getLkm()); 
    assertEquals("From: Ravintolat line: 40", r, ravintolat.anna(0)); 
    assertEquals("From: Ravintolat line: 41", r2, ravintolat.anna(1)); 
    assertEquals("From: Ravintolat line: 42", r, ravintolat.anna(2)); 
    assertEquals("From: Ravintolat line: 43", false, ravintolat.anna(1) == r); 
    assertEquals("From: Ravintolat line: 44", true, ravintolat.anna(1) == r2); 
    try {
    assertEquals("From: Ravintolat line: 45", r, ravintolat.anna(3)); 
    fail("Ravintolat: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    ravintolat.lisaa(r); 
    fail("Ravintolat: 47 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}