package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.08 14:40:05 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RavintolatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa56 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa56() throws SailoException {    // Ravintolat: 56
    Ravintolat ravintolat = new Ravintolat(); 
    Ravintola r = new Ravintola(); 
    Ravintola r2 = new Ravintola(); 
    assertEquals("From: Ravintolat line: 62", 0, ravintolat.haeLkm()); 
    ravintolat.lisaa(r); assertEquals("From: Ravintolat line: 64", 1, ravintolat.haeLkm()); 
    ravintolat.lisaa(r2); assertEquals("From: Ravintolat line: 65", 2, ravintolat.haeLkm()); 
    ravintolat.lisaa(r); assertEquals("From: Ravintolat line: 66", 3, ravintolat.haeLkm()); 
    assertEquals("From: Ravintolat line: 68", r, ravintolat.anna(0)); 
    assertEquals("From: Ravintolat line: 69", r2, ravintolat.anna(1)); 
    assertEquals("From: Ravintolat line: 70", r, ravintolat.anna(2)); 
    assertEquals("From: Ravintolat line: 71", false, ravintolat.anna(1) == r); 
    assertEquals("From: Ravintolat line: 72", true, ravintolat.anna(1) == r2); 
    try {
    assertEquals("From: Ravintolat line: 73", r, ravintolat.anna(3)); 
    fail("Ravintolat: 73 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    ravintolat.lisaa(r); 
    fail("Ravintolat: 75 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}