package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.08 14:39:58 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RavintolaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi51 */
  @Test
  public void testRekisteroi51() {    // Ravintola: 51
    Ravintola r = new Ravintola(); 
    assertEquals("From: Ravintola line: 53", 0, r.haeId()); 
    r.rekisteroi(); 
    Ravintola r2 = new Ravintola(); 
    assertEquals("From: Ravintola line: 56", 0, r2.haeId()); 
    r2.rekisteroi(); 
    int n1 = r.haeId(); 
    int n2 = r2.haeId(); 
    assertEquals("From: Ravintola line: 60", n1+1, n2); 
  } // Generated by ComTest END
}