package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.06 15:05:25 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TuoteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi57 */
  @Test
  public void testRekisteroi57() {    // Tuote: 57
    Tuote t = new Tuote(); 
    assertEquals("From: Tuote line: 59", 0, t.haeId()); 
    t.rekisteroi(); 
    Tuote t2 = new Tuote(); 
    t2.rekisteroi(); 
    int n1 = t.haeId(); 
    int n2 = t2.haeId(); 
    assertEquals("From: Tuote line: 65", n2-1, n1); 
  } // Generated by ComTest END
}