package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.02.21 23:23:21 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TuotteetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa26 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa26() throws SailoException {    // Tuotteet: 26
    Tuotteet tuotteet = new Tuotteet(); 
    Tuote t = new Tuote(); 
    Tuote t2 = new Tuote(); 
    assertEquals("From: Tuotteet line: 31", 0, tuotteet.getLkm()); 
    tuotteet.lisaa(t); assertEquals("From: Tuotteet line: 32", 1, tuotteet.getLkm()); 
    tuotteet.lisaa(t2); assertEquals("From: Tuotteet line: 33", 2, tuotteet.getLkm()); 
    tuotteet.lisaa(t); assertEquals("From: Tuotteet line: 34", 3, tuotteet.getLkm()); 
    assertEquals("From: Tuotteet line: 35", t, tuotteet.anna(0)); 
    assertEquals("From: Tuotteet line: 36", t2, tuotteet.anna(1)); 
    assertEquals("From: Tuotteet line: 37", t, tuotteet.anna(2)); 
    assertEquals("From: Tuotteet line: 38", false, tuotteet.anna(1) == t); 
    assertEquals("From: Tuotteet line: 39", true, tuotteet.anna(1) == t2); 
    try {
    assertEquals("From: Tuotteet line: 40", t, tuotteet.anna(3)); 
    fail("Tuotteet: 40 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    tuotteet.lisaa(t); assertEquals("From: Tuotteet line: 41", 4, tuotteet.getLkm()); 
    tuotteet.lisaa(t2); assertEquals("From: Tuotteet line: 42", 5, tuotteet.getLkm()); 
    try {
    tuotteet.lisaa(t); 
    fail("Tuotteet: 43 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}