package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.31 19:09:31 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TuoteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi69 */
  @Test
  public void testRekisteroi69() {    // Tuote: 69
    Tuote t = new Tuote(); 
    assertEquals("From: Tuote line: 71", 0, t.haeId()); 
    t.rekisteroi(); 
    Tuote t2 = new Tuote(); 
    t2.rekisteroi(); 
    int n1 = t.haeId(); 
    int n2 = t2.haeId(); 
    assertEquals("From: Tuote line: 77", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse150 */
  @Test
  public void testParse150() {    // Tuote: 150
    Tuote tuote = new Tuote(); 
    tuote.parse( "4|1|Quesadilla" ); 
    assertEquals("From: Tuote line: 153", 4, tuote.haeId()); 
    assertEquals("From: Tuote line: 154", true, tuote.toString().startsWith( "4|1|Quesadilla" )); 
    tuote.rekisteroi(); 
    int n = tuote.haeId(); 
    tuote.parse( "" + ( n + 20 )); 
    tuote.rekisteroi(); 
    assertEquals("From: Tuote line: 160", n + 20 + 1, tuote.haeId()); 
  } // Generated by ComTest END
}