package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.02.21 21:55:40 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TuoteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi49 */
  @Test
  public void testRekisteroi49() {    // Tuote: 49
    Tuote t = new Tuote(); 
    assertEquals("From: Tuote line: 51", 0, t.getId()); 
    t.rekisteroi(); 
    Tuote t2 = new Tuote(); 
    t2.rekisteroi(); 
    int n1 = t.getId(); 
    int n2 = t2.getId(); 
    assertEquals("From: Tuote line: 57", n2-1, n1); 
  } // Generated by ComTest END
}