package allergiainfo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import allergiainfo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.03 10:10:51 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TuoteAllergeeniTest {



  // Generated by ComTest BEGIN
  /** testParse138 */
  @Test
  public void testParse138() {    // TuoteAllergeeni: 138
    TuoteAllergeeni ta = new TuoteAllergeeni(); 
    ta.parse( "1|1|1234" ); 
    assertEquals("From: TuoteAllergeeni line: 141", 1, ta.haeTuoteID()); 
    assertEquals("From: TuoteAllergeeni line: 142", true, ta.toString().startsWith( "1|1|1234" )); 
  } // Generated by ComTest END
}